name: Runtime-build-test

on:
  issue_comment:
    types: [created, edited]

permissions:
  issues: write

jobs:
  CheckPoint:
    runs-on: ashu-runner-self-hosted
    if: |
      github.event.comment.body != '' &&
      contains(toJson(github.event.comment.body), '@Dotnet_ppc64le')
    steps:
      - name: Check if comment contains @Dotnet_ppc64le
        id: check_comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment.body || "";
            const shouldRun = comment.includes("@Dotnet_ppc64le");
            core.setOutput("should_run", shouldRun);
      - name: Stop if comment check fails
        run: |
          echo "Skipping job because @Dotnet_ppc64le not found in comment."
          exit 0

  runtime-build-test:
    need: CheckPoint
    runs-on: ashu-runner-self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Container
        run: |
          docker stop github-api && docker rm github-api
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04
      - name: Copy script
        run: |
          docker cp /root/ashutosh/api/runtime-runner/.github/workflows/runtime.sh github-api:/runtime.sh
          docker exec github-api chmod +x /runtime.sh
      - name: Build
        run: |
          docker exec github-api bash -c "/runtime.sh --ref ${{ github.event.pull_request.head.sha }} --build 2>&1 | tee /tmp/runtime-build.log; exit \${PIPESTATUS[0]}"
      - name: Test
        run: |
          docker exec github-api bash -c "/runtime.sh --ref ${{ github.event.pull_request.head.sha }} --test 2>&1 | tee /tmp/runtime-test.log; exit \${PIPESTATUS[0]}"
