name: Runtime-build-test

on:
  pull_request:
    branches:
      - workFlow

jobs:
  Runtime-Build-Test:
    name: Runtime Build and Test
    runs-on: ashu-runner-self-hosted

    steps:
      - name: Check if PR title or body contains @ASHU_JD
        id: check_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const title = pr.title || "";
            const body = pr.body || "";
            const shouldRun = title.includes("@ASHU_JD") || body.includes("@ASHU_JD");
            core.setOutput("should_run", shouldRun);

      - name: Stop if PR check fails
        if: steps.check_pr.outputs.should_run != 'true'
        run: |
          echo "Skipping job because @ASHU_JD not found in PR title/body."
          exit 0

      - name: Checkout code
        if: steps.check_pr.outputs.should_run == 'true'
        uses: actions/checkout@v4

      - name: Container
        if: steps.check_pr.outputs.should_run == 'true'
        run: |
          docker stop github-api && docker rm github-api
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04

      - name: Copy script
        if: steps.check_pr.outputs.should_run == 'true'
        run: |
          docker cp /root/ashutosh/api/runtime-runner/.github/workflows/runtime.sh github-api:/runtime.sh
          docker exec github-api chmod +x /runtime.sh

      - name: Build
        if: steps.check_pr.outputs.should_run == 'true'
        run: |
          docker exec github-api bash -c "/runtime.sh --ref ${{ github.event.pull_request.head.sha }} --build 2>&1 | tee /tmp/runtime-build.log; exit \${PIPESTATUS[0]}"

      - name: Test
        if: steps.check_pr.outputs.should_run == 'true'
        run: |
          docker exec github-api bash -c "/runtime.sh --ref ${{ github.event.pull_request.head.sha }} --test 2>&1 | tee /tmp/runtime-test.log; exit \${PIPESTATUS[0]}"
