name: crossbuild

on:
  push:
    branches:
      - try-GHA
jobs:
  cross-build:
    runs-on: ubuntu-latest
    steps:
      - name: cross-build
        run: |
          apt update && apt upgrade -y
          git config --global user.name "ashutoshjadhav8"
          git config --global user.email "ashutosh_jadhav@persistent.com"
          export ARCH=ppc64le && git clone --recurse-submodules  https://github.com/IBM/dotnet-s390x.git && cd dotnet-s390x && git apply /home/ubuntu/crossbuild.patch 
      - name: cleanup
        run: |
          ./docker/run ./dotnet-cleanup
      - name: bump
        run: |
          ./docker/run ./dotnet-bump "10.0.100-preview.6.25358.103" #its a sdk tag 
      - name: prepare
        run: |
          ./docker/run ./dotnet-prepare
      - name: build
        run: |
          ./docker/run ./dotnet-build
