name: runtime-build-test

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - workFlow
jobs:
  check-ms-bot:
    runs-on: ashu-runner-self-hosted
    steps:
      - name: Check if PR title or body
        id: check
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Body: ${{ github.event.pull_request.body }}"

          if [[ "${{ github.event.pull_request.title }}" == *"@ASH_JD"* ]] || [[ "${{ github.event.pull_request.body }}" == *"@ASH_JD"* ]]; then
            exit 0
          else
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Container
        run: |
          docker stop github-api && docker rm github-api
          docker run -dit --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --name github-api ubuntu:22.04
      - name: Copy script
        run: |
          docker cp /root/ashutosh/api/runtime-runner/.github/workflows/runtime.sh github-api:/runtime.sh
          docker exec github-api chmod +x /runtime.sh
      - name: Build
        run: |
          docker exec github-api bash -c "/runtime.sh --ref ${{ github.event.pull_request.head.sha }} --build 2>&1 | tee /tmp/runtime-build.log; exit \${PIPESTATUS[0]}"
      - name: Test
        run: |
          docker exec github-api bash -c "/runtime.sh --ref ${{ github.event.pull_request.head.sha }} --test 2>&1 | tee /tmp/runtime-test.log; exit \${PIPESTATUS[0]}"
